name: Lint Markdown

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Markdown Lint
        uses: DavidAnson/markdownlint-cli2-action@v9
        with:
          globs: '**/*.md'
